# Generated by Django 4.2.7 on 2023-12-05 17:08

from django.db import migrations, models
import django.db.models.deletion
import django_enumfield.db.fields
import enums


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Agent",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("state", django_enumfield.db.fields.EnumField(enum=enums.AgentState)),
                ("budget", models.DecimalField(decimal_places=2, max_digits=12)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Market",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "strategy",
                    django_enumfield.db.fields.EnumField(enum=enums.MarketStrategy),
                ),
                ("state", django_enumfield.db.fields.EnumField(enum=enums.MarketState)),
                ("lowerBidBound", models.IntegerField()),
                ("upperBidBound", models.IntegerField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Offer",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("amount", models.IntegerField()),
                ("offerPrice", models.DecimalField(decimal_places=2, max_digits=7)),
                ("acceptance", models.BooleanField()),
                (
                    "acceptancePrice",
                    models.DecimalField(decimal_places=2, max_digits=7),
                ),
                ("acceptanceAmount", models.IntegerField()),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="db.agent"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Period",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("periodNumber", models.IntegerField()),
                ("demand", models.IntegerField()),
                ("metDemand", models.IntegerField()),
                ("marketVolume", models.IntegerField()),
                ("ptf", models.IntegerField()),
                (
                    "market",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="db.market"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Plant",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("capacity", models.IntegerField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Portfolio",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "agent",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="db.agent"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Resource",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "energyType",
                    django_enumfield.db.fields.EnumField(enum=enums.EnergyType),
                ),
                ("name", models.CharField(max_length=20)),
                ("fuelCost", models.DecimalField(decimal_places=1, max_digits=5)),
                ("emission", models.DecimalField(decimal_places=1, max_digits=5)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Simulation",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=20)),
                (
                    "mode",
                    django_enumfield.db.fields.EnumField(enum=enums.SimulationMode),
                ),
                (
                    "state",
                    django_enumfield.db.fields.EnumField(enum=enums.SimulationState),
                ),
                (
                    "periodType",
                    django_enumfield.db.fields.EnumField(enum=enums.PeriodType),
                ),
                ("periodNumber", models.IntegerField()),
                ("currentPeriod", models.IntegerField()),
                (
                    "Market",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="db.market"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.DeleteModel(
            name="Product",
        ),
        migrations.DeleteModel(
            name="User",
        ),
        migrations.AddField(
            model_name="plant",
            name="portfolio",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="db.portfolio"
            ),
        ),
        migrations.AddField(
            model_name="plant",
            name="resource",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="db.resource"
            ),
        ),
        migrations.AddField(
            model_name="offer",
            name="period",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="db.period"
            ),
        ),
        migrations.AddField(
            model_name="offer",
            name="resource",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="db.resource"
            ),
        ),
        migrations.AddField(
            model_name="agent",
            name="simulation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="db.simulation"
            ),
        ),
    ]
